# Generated by Django 3.0.3 on 2020-02-21 01:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endgame', '0002_auto_20200220_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date')),
                ('estate', models.CharField(default='E', max_length=2)),
                ('player_id_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IX_PLAYER1', to='endgame.Player')),
                ('player_id_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IX_PLAYER2', to='endgame.Player')),
            ],
        ),
    ]
