# Generated by Django 3.0.3 on 2020-02-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endgame', '0003_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='estate',
            field=models.CharField(default='E', max_length=2, verbose_name='Game status'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_id_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REL_PLAYER1_GAME', to='endgame.Player', verbose_name='Player one'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_id_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REL_PLAYER2_GAME', to='endgame.Player', verbose_name='Player two'),
        ),
    ]
