# Generated by Django 3.0.3 on 2020-02-21 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endgame', '0004_auto_20200220_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_id_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REL_PLAYER1_GAME', to='endgame.Player', verbose_name='Player one'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_id_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REL_PLAYER2_GAME', to='endgame.Player', verbose_name='Player two'),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Enter your nickname'),
        ),
    ]
