# Generated by Django 3.0.3 on 2020-02-23 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('endgame', '0005_auto_20200221_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Object name')),
                ('state', models.CharField(default='A', max_length=2, verbose_name='Option status')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_win',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REL_PLAYER3_GAME', to='endgame.Player', verbose_name='Winning player'),
        ),
        migrations.CreateModel(
            name='HierarchyOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REL_OPC2_HIERARCHI', to='endgame.Options', unique=True, verbose_name='Recessive option')),
                ('father_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='REL_OPC1_HIERARCHI', to='endgame.Options', unique=True, verbose_name='Dominant option')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player_one_opc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REL_OPC1_GAME', to='endgame.Options', verbose_name='Player one option'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two_opc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REL_OPC2_GAME', to='endgame.Options', verbose_name='Player two option'),
        ),
    ]
